import os
import re
import sys
import glob
import scipy
sys.path.append(os.getcwd() + "/../")
import mycasaimaging_tools as myim


dir_data = "../../proposal/alma_cycle6/"


done = glob.glob(dir_data + "../eps/")
if not done:
    os.mkdir(dir_data + "../eps/")


#####################
### Main Procedure
#####################

### ESO 148
ra_center = "23:15:46.877"
dec_center = "-59.03.14.935"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-5., 5.]
ylim = [5., -5.]
clim = [12500, 12650]
value = None
imagename_contour = "eso148_co32.moment0.fits"
imagename_color = "eso148_co32.moment1.fits"
title = "ESO 148"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/eso148.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### ESO 286
ra_center = "20:58:26.799"
dec_center = "-42.39.00.307"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-3.5, 3.5]
ylim = [3.5, -3.5]
clim = [12230, 12450]
value = None
imagename_contour = "eso286_co32.moment0.fits"
imagename_color = "eso286_co32.moment1.fits"
title = "ESO 286"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/eso286.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### IRAS 05189
ra_center = "05:21:01.350"
dec_center = "-25.21.45.280"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-2., 2.]
ylim = [2., -2.]
clim = [12230, 12370]
value = None
imagename_contour = "iras05189_co32.moment0.fits"
imagename_color = "iras05189_co32.moment1.fits"
title = "IRAS 05189"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/iras05189.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### IRAS 12112
ra_center = "12:13:46.15"
dec_center = "02.48.43.2"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-3., 3.]
ylim = [2.5, -3.5]
clim = [19850, 20400]
value = None
imagename_contour = "iras12112_co32.moment0.fits"
imagename_color = "iras12112_co32.moment1.fits"
title = "IRAS 12112"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/iras12112.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### IRAS 13120
ra_center = "13:15:06.343"
dec_center = "-55.09.26.737"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-4., 4.]
ylim = [4., -4.]
clim = [8850, 9250]
value = None
imagename_contour = "iras13120_co32.moment0.fits"
imagename_color = "iras13120_co32.moment1.fits"
title = "IRAS 13120"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/iras13120.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### IRAS 17207
ra_center = "17:23:21.940"
dec_center = "-00.17.01.868"
contour = [0.0025, 0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-4.5, 4.5]
ylim = [4.5, -4.5]
clim = [12090, 12670]
value = None
imagename_contour = "irasf17207_co32.moment0.fits"
imagename_color = "irasf17207_co32.moment1.fits"
title = "IRAS 17207"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/iras17207.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### NGC 34
ra_center = "00:11:06.55"
dec_center = "-12.06.27.5"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-3., 3.]
ylim = [3., -3.]
clim = [5450, 6000]
value = None
imagename_contour = "ngc34_co32.moment0.fits"
imagename_color = "ngc34_co32.moment1.fits"
title = "NGC 34"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/ngc34.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### NGC 1614
ra_center = "04:34:00.035"
dec_center = "-08.34.44.105"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-8., 8.]
ylim = [8., -8.]
clim = [4485, 4835]
value = None
imagename_contour = "ngc1614_co32.moment0.fits"
imagename_color = "ngc1614_co32.moment1.fits"
title = "NGC 1614"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/ngc1614.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### NGC 3110
ra_center = "10:04:02.083"
dec_center = "-06.28.29.103"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-30., 30.]
ylim = [30., -30.]
clim = [-165, 275]
value = None
imagename_contour = "ngc3110_co21.moment0.fits"
imagename_color = "ngc3110_co21.moment1.fits"
title = "NGC 3110"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/ngc3110.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### NGC 3256
ra_center = "10:27:51.240"
dec_center = "-43.54.18.670"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-12., 12.]
ylim = [12., -12.]
clim = [2650, 2950]
value = None
imagename_contour = "ngc3256_co32.moment0.fits"
imagename_color = "ngc3256_co32.moment1.fits"
title = "NGC 3256"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/ngc3256.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### NGC 6240
ra_center = "16:52:58.823"
dec_center = "02.24.03.920"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-6., 6.]
ylim = [6., -6.]
clim = [6965, 7505]
value = None
imagename_contour = "ngc6240_co32.moment0.fits"
imagename_color = "ngc6240_co32.moment1.fits"
title = "NGC 6240"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/ngc6240.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### VV 114
ra_center = "01:07:47.145"
dec_center = "-17.30.25.759"
contour = [0.005, 0.01, 0.02, 0.04, 0.08, 0.16, 0.32, 0.64, 0.96]
xlim = [-18., 18.]
ylim = [18., -18.]
clim = [5665, 6145]
value = None
imagename_contour = "vv114_co32.moment0.fits"
imagename_color = "vv114_co32.moment1.fits"
title = "VV 114"
colorscale = "rainbow"
color_contour = "black"
color_beam = "black"
colorlog = False
colorbar = False
colorbar_label = "(Jy km s$^{-1}$)"
output = "../eps/vv114.eps"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
