import os
import re
import sys
import glob
import scipy
sys.path.append(os.getcwd() + "/../")
import mycasaimaging_tools as myim
import matplotlib.pyplot as plt
plt.ioff()

dir_data = "/Users/saito/data/myproj_published/proj_phangs02_feather/products/"
ra_center = "01:36:41.770"
dec_center = "15.46.58.663"
xlim = [-170, 170]
ylim = [170, -170]
value = None

done = glob.glob(dir_data + "../figures/")
if not done:
    os.mkdir(dir_data + "../figures/")

#####################
### Main Procedure
#####################
### common
#
imagename_contour = "test0607_skymodel_2p5.fits"
contour = [0.009/0.528614]
colorscale = "rainbow"
color_contour = "black"
color_beam = "white"
colorlog = False
colorbar = True

### north mosaic
#
imagename_color = "test06_12m+7m_br_2p5.fits"
clim = [-0.01,0.50]
title = "South: 12m+7m Clean Image PBcor"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_12m+7m_br_2p5.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_12m+7m_br.pb.fits"
clim = [0.0,1.0]
title = "South: 12m+7m PB"
colorbar_label = ""
output = "../figures/test06_12m+7m_br.pb.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_12m+7m_br_2p5.diff.fits"
clim = [-0.015,0.015]
title = "South: 12m+7m Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_12m+7m_br_2p5.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_featherfirst_sd1p0_br.fits"
clim = [-0.01,0.50]
title = "South: FeatherFirst"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_featherfirst_sd1p0_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_Pbcorrfirst_sd1p0_br.fits"
clim = [-0.01,0.50]
title = "South: PBcorrFirst with full TP"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_pbcorrfirst_sd1p0_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_pbcorrfirst_sd1p0_tpcut_br.fits"
clim = [-0.01,0.50]
title = "South: PBcorrFirst with clipped TP"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_pbcorrfirst_sd1p0_tpcut_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_featherfirst_sd1p0_br.diff.fits"
clim = [-0.015,0.015]
title = "South: FeatherFirst - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_featherfirst_sd1p0_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_pbcorrfirst_sd1p0_br.diff.fits"
clim = [-0.015,0.015]
title = "South: PBcorrFirst with full TP - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_pbcorrfirst_sd1p0_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test06_pbcorrfirst_sd1p0_tpcut_br.diff.fits"
clim = [-0.015,0.015]
title = "South: PBcorrFirst with clipped TP - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test06_pbcorrfirst_sd1p0_tpcut_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)


### north mosaic
#
imagename_color = "test07_12m+7m_br_2p5.fits"
clim = [-0.01,0.50]
title = "North: 12m+7m Clean Image PBcor"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_12m+7m_br_2p5.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_12m+7m_br.pb.fits"
clim = [0.0,1.0]
title = "North: 12m+7m PB"
colorbar_label = ""
output = "../figures/test07_12m+7m_br.pb.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_12m+7m_br_2p5.diff.fits"
clim = [-0.015,0.015]
title = "North: 12m+7m Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_12m+7m_br_2p5.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_featherfirst_sd1p0_br.fits"
clim = [-0.01,0.50]
title = "North: FeatherFirst with full TP"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_featherfirst_sd1p0_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_Pbcorrfirst_sd1p0_br.fits"
clim = [-0.01,0.50]
title = "North: PBcorrFirst with full TP"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_pbcorrfirst_sd1p0_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_pbcorrfirst_sd1p0_tpcut_br.fits"
clim = [-0.01,0.50]
title = "North: PBcorrFirst with clipped TP"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_pbcorrfirst_sd1p0_tpcut_br.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_featherfirst_sd1p0_br.diff.fits"
clim = [-0.015,0.015]
title = "North: FeatherFirst - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_featherfirst_sd1p0_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_pbcorrfirst_sd1p0_br.diff.fits"
clim = [-0.015,0.015]
title = "North: PBcorrFirst with full TP - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_pbcorrfirst_sd1p0_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test07_pbcorrfirst_sd1p0_tpcut_br.diff.fits"
clim = [-0.015,0.015]
title = "North: PBcorrFirst with clipped TP - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test07_pbcorrfirst_sd1p0_tpcut_br.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

# feather_then_merged field
#
imagename_color = "test0607_featherfirst_then_merge.fits"
clim = [-0.01,0.50]
title = "FeatherFirst then Merged Image"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_featherfirst_then_merge.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_pbcorrfirst_then_merge.fits"
clim = [-0.01,0.50]
title = "PBcorrFirst then Merged Image"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_pbcorrfirst_then_merge.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_featherfirst_then_merge.diff.fits"
clim = [-0.015,0.015]
title = "FeatherFirst then Merged Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_featherfirst_then_merge.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_pbcorrfirst_then_merge.diff.fits"
clim = [-0.015,0.015]
title = "PBcorrFirst then Merged Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_pbcorrfirst_then_merge.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

# merged_then_feather field
#
imagename_color = "test0607_12m+7m_merge.fits"
clim = [-0.01,0.50]
title = "Merged 12m+7m Clean Image PBcor"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_12m+7m_merge.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_merge_then_pbcorrfirst.fits"
clim = [-0.01,0.50]
title = "Merged then PBcorrFirst Image"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_merge_then_pbcorrfirst.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_12m+7m_merge.diff.fits"
clim = [-0.015,0.015]
title = "Merged 12m+7m Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_12m+7m_merge.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_merge_then_pbcorrfirst.diff.fits"
clim = [-0.015,0.015]
title = "Merged then PBcorrFirst Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_merge_then_pbcorrfirst.diff.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

### common for small fits
#
colorbar = False
xlim = [-110, 110]
ylim = [30, -30]
#
imagename_color = "test0607_12m+7m_merge.diff_clip.fits"
clim = [-0.015,0.015]
title = "Zoom: Merged 12m+7m Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_12m+7m_merge.diff_clip.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_featherfirst_then_merge.diff_clip.fits"
clim = [-0.015,0.015]
title = "Zoom: FeatherFirst then Merged Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_featherfirst_then_merge.diff_clip.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_pbcorrfirst_then_merge.diff_clip.fits"
clim = [-0.015,0.015]
title = "Zoom: PBcorrFirst then Merged Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_pbcorrfirst_then_merge.diff_clip.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)
#
imagename_color = "test0607_merge_then_pbcorrfirst.diff_clip.fits"
clim = [-0.015,0.015]
title = "Zoom: Merged then PBcorrFirst Image - Input"
colorbar_label = "(Jy beam$^{-1}$)"
output = "../figures/test0607_merge_then_pbcorrfirst.diff_clip.png"
myim.fits2eps(dir_data = dir_data,
              imagename_color = imagename_color,
              imagename_contour = imagename_contour,
              ra_center = ra_center,
              dec_center = dec_center,
              title = title,
              colorbar_label = colorbar_label,
              output = output,
              colorscale = colorscale,
              colorlog = colorlog,
              color_contour = color_contour,
              color_beam = color_beam,
              colorbar = colorbar,
              value = value,
              contour = contour,
              xlim = xlim,
              ylim = ylim,
              clim = clim)

os.system("rm -rf *.last")
